# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ScienceFlightPlanner
                                 A QGIS plugin
 This plugin allows to create flight plans based on existing waypoints and paths.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-22
        copyright            : (C) 2022 by Leon Krüger, Lars Reining, Jonas Schröter, Moritz Vogel, Hannah Willkomm
        email                : leon.krueger@stud.tu-darmstadt.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ScienceFlightPlanner class from file ScienceFlightPlanner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .science_flight_planner import ScienceFlightPlanner

    return ScienceFlightPlanner(iface)
